import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Config from "@/components/Config"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Wey Fe",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-[#f4f5f7]`}>
                <Config>{children}</Config>
            </body>
        </html>
    )
}
